source "https://rubygems.org"

gem "jekyll", "~> 3.9"

gem "kramdown-parser-gfm"
gem 'bigdecimal'
gem "csv"
gem "logger"
gem "base64"
gem 'wdm' if Gem.win_platform?


group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-remote-theme"
  gem "jekyll-webp"
  gem "jekyll-seo-tag"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end
